In [26]:
import gym
import numpy as np

env = gym.make("FrozenLake-v1", is_slippery=False)

LEARNING_RATE = 0.1
DISCOUNT = 0.95
EPISODES = 10000

epsilon = 1.0
epsilon_decay = 0.0001

In [20]:
frozenlake_q_table = np.zeros((env.observation_space.n, env.action_space.n))

print(frozenlake_q_table)
print(frozenlake_q_table.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(16, 4)


In [30]:
rewards_per_episode = []

for episode in range(EPISODES):
    state, info = env.reset()
    done = False
    total_reward = 0

    while not done:
        if np.random.random() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(frozenlake_q_table[state])

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        current_q = frozenlake_q_table[state, action]
        max_future_q = np.max(frozenlake_q_table[new_state])

        new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (
            reward + DISCOUNT * max_future_q
        )

        frozenlake_q_table[state, action] = new_q

        state = new_state
        total_reward += reward

    epsilon = max(epsilon - epsilon_decay, 0)
    rewards_per_episode.append(total_reward)

    

env.close()

print("\nFinal FrozenLake Q-table:")
print(frozenlake_q_table)


Final FrozenLake Q-table:
[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378094]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]
