In [1]:
import gym
import numpy as np

env = gym.make("Taxi-v3")

state, info = env.reset()
LEARNING_RATE=0.1
DISCOUNT=0.95
EPISODES=10000
epsilon = 1.0
epsilon_decay = 0.0001

print("state:", state)
print("action space:", env.action_space)
print("observation space:", env.observation_space)


state: 409
action space: Discrete(6)
observation space: Discrete(500)


Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [2]:
q_table = np.zeros((env.observation_space.n , env.action_space.n))
print(q_table.shape)

(500, 6)


In [3]:
for episode in range(EPISODES):
    state, info = env.reset()
    done = False
    total_reward = 0
    steps = 0

    while not done:
        if np.random.random() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        new_state, reward, terminated, truncated, info = env.step(action)

        done = terminated or truncated

        current_q = q_table[state, action]
        max_future_q = np.max(q_table[new_state])

        new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (
            reward + DISCOUNT * max_future_q
        )

        q_table[state, action] = new_q

        state = new_state
        total_reward += reward
        steps += 1

    epsilon = max(epsilon - epsilon_decay, 0)


print("\nFinal Q-table:")
print(q_table)

env.close()

C:\Users\admin\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):



Final Q-table:
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 2.75199992  3.94947731  2.75200056  3.94947729  5.20997639 -5.05052287]
 [ 7.93349161  9.40365188  7.93349068  9.40367041 10.9512375   0.40367499]
 ...
 [10.93708293 12.58025    10.93222249  9.38231892  1.94184786  1.92913144]
 [ 5.20308148  6.52510602  5.18935671  6.53681719 -3.84355686 -3.80341322]
 [16.09998384 14.29485036 16.09963076 18.          7.0998821   7.09991275]]


In [5]:
import time

test_env = gym.make("Taxi-v3", render_mode="human")

for test in range(5):
    state, info = test_env.reset()
    done = False
    total_reward = 0
    steps = 0

    print("Test:", test + 1)

    while not done:
        time.sleep(0.5)

        action = np.argmax(q_table[state])

        new_state, reward, terminated, truncated, info = test_env.step(action)

        total_reward += reward
        steps += 1
        done = terminated or truncated
        state = new_state

    print("Reward:", total_reward)
    print("Steps:", steps)
    print("----------------")

test_env.close()

Test: 1
Reward: 10
Steps: 11
----------------
Test: 2
Reward: 4
Steps: 17
----------------
Test: 3
Reward: 11
Steps: 10
----------------
Test: 4
Reward: 14
Steps: 7
----------------
Test: 5
Reward: 7
Steps: 14
----------------
